import { Inter, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Home/Header";
import Footer from "./components/Home/Footer";
import Download from "./components/Home/Download";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Muhlah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header />
        <main className="flex-grow">{children}</main> {/* Page content */}
        <Download />
        <Footer /> {/* Footer */}
      </body>
    </html>
  );
}
